### PR TITLE
Fix USB Thumb drive detection

### PR DESCRIPTION
**Pull request by SibrenVasse**
Made a small mistake while modifying the previous pull request.

### CODE REVIEW

**Comment by jsamr** [comment]
@SibrenVasse Oh OK ; I'll squash this commit with your previous PR !

**Comment by jsamr** [comment]
@SibrenVasse I have encountered an issue with the `deviceIsThumb` function.

I my distro, last build, the output of `udevadm info --query=property --path="$deviceName"` for any USB thumb drive has no `ID_DRIVE_THUMB` property, so I always have "no USB thumb drive found" message:

```
DEVLINKS=/dev/disk/by-path/pci-0000:03:00.0-usb-0:2:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-Sony_Storage_Media_FBA3605FFF25B1-0:0 /dev/disk/by-uuid/2019-01-03-18-10-47-00 /dev/disk/by-label/MJRO1802
DEVNAME=/dev/sdd
DEVPATH=/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/usb3/3-2/3-2:1.0/host10/target10:0:0/10:0:0:0/block/sdd
DEVTYPE=disk
ID_BUS=usb
ID_FS_APPLICATION_ID=MANJARO\x20LINUX\x20LIVE\x2fRESCUE\x20CD
ID_FS_BOOT_SYSTEM_ID=EL\x20TORITO\x20SPECIFICATION
ID_FS_LABEL=MJRO1802
ID_FS_LABEL_ENC=MJRO1802
ID_FS_PUBLISHER_ID=MANJARO\x20LINUX\x20\x3cHTTPS:\x2f\x2fWWW.MANJARO.ORG\x2f\x3e
ID_FS_TYPE=iso9660
ID_FS_USAGE=filesystem
ID_FS_UUID=2019-01-03-18-10-47-00
ID_FS_UUID_ENC=2019-01-03-18-10-47-00
ID_INSTANCE=0:0
ID_MODEL=Storage_Media
ID_MODEL_ENC=Storage\x20Media\x20\x20\x20
ID_MODEL_ID=05b8
ID_PART_TABLE_TYPE=dos
ID_PATH=pci-0000:03:00.0-usb-0:2:1.0-scsi-0:0:0:0
ID_PATH_TAG=pci-0000_03_00_0-usb-0_2_1_0-scsi-0_0_0_0
ID_REVISION=1.00
ID_SERIAL=Sony_Storage_Media_FBA3605FFF25B1-0:0
ID_SERIAL_SHORT=FBA3605FFF25B1
ID_TYPE=disk
ID_USB_DRIVER=usb-storage
ID_USB_INTERFACES=:080650:
ID_USB_INTERFACE_NUM=00
ID_VENDOR=Sony
ID_VENDOR_ENC=Sony\x20\x20\x20\x20
ID_VENDOR_ID=054c
MAJOR=8
MINOR=48
SUBSYSTEM=block
TAGS=:systemd:
USEC_INITIALIZED=7564822637
```

I think the most sensible behaviour would be to first check if `$isThumb` is empty and consider device as thumb if it is. Or even better, find a more reliable way to check for thumb property, perhaps somewhere in the `/sys/block/` path.

**Comment by SibrenVasse** [comment]
So after some digging where the ID_DRIVE_THUMB property came from in the first place:

> /usr/lib/udev/rules.d/80-udisks2.rules

```
# USB stick / thumb drives
#
SUBSYSTEMS=="usb", ENV{ID_VENDOR}=="*Kingston*", ENV{ID_MODEL}=="*DataTraveler*", ENV{ID_DRIVE_THUMB}="1"
SUBSYSTEMS=="usb", ENV{ID_VENDOR}=="*SanDisk*", ENV{ID_MODEL}=="*Cruzer*", ENV{ID_CDROM}!="1", ENV{ID_DRIVE_THUMB}="1"
SUBSYSTEMS=="usb", ENV{ID_VENDOR}=="HP", ENV{ID_MODEL}=="*v125w*", ENV{ID_DRIVE_THUMB}="1"
SUBSYSTEMS=="usb", ENV{ID_VENDOR_ID}=="13fe", ENV{ID_MODEL}=="*Patriot*", ENV{ID_DRIVE_THUMB}="1"
SUBSYSTEMS=="usb", ENV{ID_VENDOR}=="*JetFlash*", ENV{ID_MODEL}=="*Transcend*", ENV{ID_DRIVE_THUMB}="1"
```
Which does seem rather limited. Your Sony stick for example does not match these conditions. (I've got a Kingston Datatraveler, which does) I've tried a different USB stick I had lying around and that did indeed also fail.

For every device **not** matching the above, ID_DRIVE_THUMB is not present. I've not found a more reliable way to detect the difference between an external HDD and a thumb drive in sysfs. And if udev uses a whitelist, there probably isn't...

So I think we have to change bootiso's logic:

### ID_THUMB_DRIVE is not present
- If --force-thumb-check is set: failandexit.
- If --force-thumb-check is not set: warn and proceed.
### ID_THUMB_DRIVE is present
- Continue

This does make the check less useful though. What do you think?

**Comment by jsamr** [comment]
@SibrenVasse yeah ... the "check" word becomes a bit abusive, since it's just a whitelist matching rule.

I agree with reversing the flag as you suggested.
But since we are removing a flag, we'll have to increment a major release&mdash;as per the semantic versioning standard.

**Comment by jsamr** [comment]
@SibrenVasse Actually ... I'm considering removing the check completely. A whitelist check is nothing standard, and highly exposed to human errors... I don't want the API to sell the illusion of a reliable check ; and don't want someone to risk anything because of this tool.

**Comment by SibrenVasse** [comment]
> But since we are removing a flag, we'll have to increment a major release—as per the semantic versioning standard.

Well no, this has never left 'next' right?

**Comment by jsamr** [comment]
> Well no, this has never left 'next' right?

Doh, you are right.

**Pull request merged**
